### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter on JVM versions >=9

### ISSUE THREAD

**Issue by Sorixelle** [gwen-interpreter/gwen-gpm#1]
JAXB was moved out into a module in Java 9. As a result, checksum matching fails, as Gwen-gpm uses `DatatypeConverter.printHexBinary` to convert the checksum byte array to a string in a few places (FileIO, L128, L150).

A current workaround is to either use Java 8, or add the JVM argument `--add-modules java.se.ee` when running Gwen-gpm.

**Comment by bjuric** [comment]
Package manager updated to use [commons-codec Hex](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Hex.html#encodeHexString-byte:A-) converter instead of deprecated DatatypeConverter.

The latest gwen-workspace.zip package includes the fix here: https://github.com/gwen-interpreter/gwen-web/releases/latest

Please try it out and close issue if all good.

Thanks

**Comment by Sorixelle** [comment]
Yep, all good now. :+1:
